services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n-data:/home/node/.n8n
    environment:
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_USER=admn
      - DB_MYSQLDB_PASSWORD=p@ssw0rd
      # Optional Redis config for queues/caching
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      # If Redis auth is enabled, add:
      # - QUEUE_BULL_REDIS_PASSWORD=yourpassword
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - mysql
      - redis
      - mqtt
    networks:
      - n8n-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=admn
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
    networks:
      - n8n-network

  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    command: [ "redis-server", "--appendonly", "yes", "--loglevel", "verbose" ]
    networks:
      - n8n-network

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mqtt-data:/mosquitto/data
      - ./data/mqtt-logs:/mosquitto/log
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
