@MCPSESSIONID = 26b121327da540e192fc5c3f076cf158

###
POST http://localhost:6789/mcp
Content-Type: application/json
Accept: application/json, text/event-stream

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
      "protocolVersion": "2024-11-05",
      "capabilities": {},
      "clientInfo": {
        "name": "curl-client",
        "version": "1.0.0"
      }
    }
}

# Copy the mcp-session-id from the response above and set it to the variable MCPSESSIONID for subsequent requests

###
POST http://localhost:6789/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{MCPSESSIONID}}

{
    "jsonrpc": "2.0",
    "method": "notifications/initialized"
}

###
POST http://localhost:6789/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{MCPSESSIONID}}

{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/list",
    "params": {}
}

###
POST http://localhost:6789/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{MCPSESSIONID}}

{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "tools/call",
    "params": {
        "name": "encrypt",
        "arguments": {
            "params": {
                "text": "Hello, World!"
            }
        }
    }
}

###
POST http://localhost:6789/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{MCPSESSIONID}}

{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "tools/call",
    "params": {
        "name": "encrypt",
        "arguments": {
            "params": {
                "text": 574
            }
        }
    }
}

###
POST http://localhost:6789/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{MCPSESSIONID}}

{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "tools/call",
    "params": {
        "name": "encrypt",
        "arguments": {
            "params": {
                "text": {
                    "sum": 574
                }
            }
        }
    }
}